### ISSUE TITLE
stl files?

### ISSUE THREAD

**Issue by jneilliii** [xSnowHeadx/MinimalClock#2]
Since you're boycotting Thingiverse, have you considered posting the STL files elsewhere, like here or PrusaPrinters.org, which might back up the license?

**Comment by xSnowHeadx** [comment]
Hi,

every kind of public upload can't prevent the printshops from stealing the designs and sell the prints for profit.
That's why I send the files only on demand. So I can check if the asking guy is also active in the community and is sharing own software ore hardware projects. In this case I send the files to his submitted mail address (may be a disposable one too) hoping he's using them for private purposes only.
I did this meanwhile about over 200 times and the additional effort it's worth to me to stop the misuse by the ebay-parasites.

Regards
SnowHead

**Comment by jneilliii** [comment]
Well, as you can see from my github profile, I'm very active in open source software, specifically around octoprint and its plugins. Any chance you can send me those files to the email linked to my github profile?

**Comment by xSnowHeadx** [comment]
No problem. The files are on their way.
